# Generated by Django 4.2.1 on 2023-08-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleplayingroom",
            name="gpt_role_en",
            field=models.CharField(
                blank=True,
                help_text="GPT 프롬프트에 직접적으로 활용됩니다. 비워두시면, gpt_role 필드를 번역하여 자동 반영됩니다.",
                max_length=100,
                verbose_name="GPT 역할 (영문)",
            ),
        ),
        migrations.AlterField(
            model_name="roleplayingroom",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-US", "English"),
                    ("ja-JP", "Japanese"),
                    ("zh-CN", "Chinese"),
                    ("es-ES", "Spanish"),
                    ("fr-FR", "French"),
                    ("de-DE", "German"),
                    ("ru-RU", "Russian"),
                ],
                default="en-US",
                max_length=10,
                verbose_name="대화 언어",
            ),
        ),
        migrations.AlterField(
            model_name="roleplayingroom",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "초급"), (2, "고급")], default=1, verbose_name="레벨"
            ),
        ),
        migrations.AlterField(
            model_name="roleplayingroom",
            name="my_role_en",
            field=models.CharField(
                blank=True,
                help_text="GPT 프롬프트에 직접적으로 활용됩니다. 비워두시면, my_role 필드를 번역하여 자동 반영됩니다.",
                max_length=100,
                verbose_name="내 역할 (영문)",
            ),
        ),
        migrations.AlterField(
            model_name="roleplayingroom",
            name="situation_en",
            field=models.CharField(
                blank=True,
                help_text="GPT 프롬프트에 직접적으로 활용됩니다. 비워두시면, situation 필드를 번역하여 자동 반영됩니다.",
                max_length=100,
                verbose_name="상황 (영문)",
            ),
        ),
    ]
